version: '3'
services:
    nginx:
        image: nginx:alpine
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/usr/share/nginx/html:ro
        ports:
            - "80:80"
        depends_on:
            - php
    php:
        image: php:fpm-alpine
        deploy:
            replicas: 5
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        volumes:
            - ./:/usr/share/nginx/html:ro